// frontend-vue/src/views/Login.vue
<!--
  P2.2 登录页 · 版A 企业浅色
  布局按旧版（左视频 50% + 右表单 50% 圆角卡片），配色全部用新版版A浅色 token。
  Element Plus 组件优先（el-input / el-button / el-message）。
-->
<template>
  <div class="login-page">
    <div class="login-card">
      <!-- 左侧：视频媒体区（布局沿用旧版） -->
      <div class="login-media">
        <video class="login-video" src="/login-video.mp4" autoPlay muted loop playsInline />
        <div class="login-media-overlay" />
        <div class="login-brand">
          <span class="brand-logo">yika</span>
          <span class="brand-ai">AI</span>
        </div>
        <div class="login-media-caption">AI 驱动的企业业务集成平台</div>
      </div>

      <!-- 右侧：登录表单（新版浅色） -->
      <div class="login-form-side">
        <div class="login-form-inner">
          <p class="login-eyebrow">内部协作平台</p>
          <h2 class="login-title">欢迎回来</h2>
          <p class="login-subtitle">登录以继续协作</p>

          <el-form @submit.prevent="onLogin">
            <el-form-item>
              <el-input v-model="form.username" size="large" placeholder="请输入用户名" autocomplete="username" />
            </el-form-item>
            <el-form-item>
              <el-input v-model="form.password" size="large" type="password" placeholder="请输入密码" show-password autocomplete="current-password" />
            </el-form-item>
            <el-alert v-if="err" :title="err" type="error" :closable="false" class="login-error" />
            <el-button type="primary" size="large" class="login-submit" :loading="loading" @click="onLogin">
              登 录
            </el-button>
          </el-form>

          <p class="login-footer">账号由管理员开通 · 纯内部使用</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const router = useRouter()
const auth = useAuthStore()
const form = ref({ username: '', password: '' })
const loading = ref(false)
const err = ref('')

async function onLogin() {
  if (!form.value.username.trim() || !form.value.password) {
    err.value = '请输入用户名和密码'
    return
  }
  loading.value = true
  err.value = ''
  try {
    await auth.login(form.value.username, form.value.password)
    router.push('/portal')
  } catch (e: any) {
    err.value = e.response?.data?.error?.message || '登录失败，请检查用户名密码'
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
/* 布局沿旧版：全屏浅色底 + 居中大圆角卡片 + 左视频右表单 50:50 */
.login-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--bg);
  padding: 24px;
}
.login-card {
  display: flex;
  width: min(1000px, 100%);
  min-height: min(620px, calc(100vh - 48px));
  border-radius: 20px;
  overflow: hidden;
  background: var(--surface);
  border: 1px solid var(--border);
  box-shadow: var(--shadow);
}
/* 左：视频 */
.login-media {
  position: relative;
  flex: 1 1 50%;
  overflow: hidden;
}
.login-video {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}
.login-media-overlay {
  position: absolute;
  inset: 0;
  pointer-events: none;
  background: linear-gradient(180deg, rgba(51, 112, 255, 0.25) 0%, transparent 40%, rgba(0, 0, 0, 0.4) 100%);
}
.login-brand {
  position: absolute;
  top: 28px;
  left: 30px;
  display: flex;
  align-items: center;
  gap: 2px;
  font-weight: 800;
  font-size: 22px;
  color: #fff;
  text-shadow: 0 1px 6px rgba(0, 0, 0, 0.3);
}
.brand-ai { color: #ffd76a; }
.login-media-caption {
  position: absolute;
  left: 30px;
  bottom: 28px;
  color: rgba(255, 255, 255, 0.9);
  font-size: 13px;
  letter-spacing: 0.08em;
}
/* 右：表单（新版浅色） */
.login-form-side {
  flex: 1 1 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 48px 56px;
  background: var(--surface);
}
.login-form-inner { width: 100%; max-width: 340px; }
.login-eyebrow {
  font-size: 12px;
  letter-spacing: 0.22em;
  text-transform: uppercase;
  color: var(--text3);
  margin-bottom: 12px;
}
.login-title {
  font-size: 28px;
  font-weight: 700;
  color: var(--text);
  margin-bottom: 8px;
}
.login-subtitle {
  font-size: 14px;
  color: var(--text2);
  margin-bottom: 28px;
}
.login-error { margin-bottom: 14px; }
.login-submit { width: 100%; margin-top: 4px; }
.login-footer {
  margin-top: 28px;
  text-align: center;
  font-size: 12px;
  color: var(--text3);
}
@media (max-width: 860px) {
  .login-media { display: none; }
  .login-card { min-height: auto; }
  .login-form-side { padding: 40px 32px; }
}
</style>

// frontend/src/pages/Login.tsx
import { useState, type FormEvent } from "react";
import { useAuth } from "../context/AuthContext";
import "./login.css";

/* GateAI 品牌 logo：Gate(白) + AI(蓝) + 蓝色四角星
   深色适配版，全部内联实现，无外部图片依赖 */
function GateAILogo({ size = 17 }: { size?: number }) {
  return (
    <span className="gateai-logo" style={{ fontSize: size }}>
      <svg
        width={size * 1.15}
        height={size * 1.15}
        viewBox="0 0 24 24"
        className="gateai-star"
        aria-hidden="true"
      >
        <path
          d="M12 2.4c.55 4.3 5 8.7 9.3 9.3-4.3.6-8.75 5-9.3 9.3-.55-4.3-5-8.7-9.3-9.3C7 11.1 11.45 6.7 12 2.4Z"
          fill="currentColor"
        />
      </svg>
      <span className="gateai-gate">Gate</span>
      <span className="gateai-ai">AI</span>
    </span>
  );
}

export default function Login() {
  const { login } = useAuth();
  const [u, setU] = useState("");
  const [p, setP] = useState("");
  const [err, setErr] = useState("");
  const [loading, setLoading] = useState(false);
  const [showPwd, setShowPwd] = useState(false);

  async function submit(e: FormEvent) {
    e.preventDefault();
    if (!u.trim() || !p) {
      setErr("请输入用户名和密码");
      return;
    }
    setLoading(true);
    setErr("");
    try {
      await login(u, p);
      window.location.href = "/";
    } catch {
      setErr("登录失败，请检查用户名密码");
      setLoading(false);
    }
  }

  return (
    <div className="login-page">
      <div className="login-card">
        {/* 左侧：视频 + 品牌 */}
        <div className="login-media">
          <video
            className="login-video"
            src="/login-video.mp4"
            autoPlay
            muted
            loop
            playsInline
          />
          <div className="login-media-overlay" />
          <div className="login-brand">
            <GateAILogo size={20} />
          </div>
          <div className="login-media-caption">AI 驱动的团队协作平台</div>
        </div>

        {/* 右侧：登录表单 */}
        <div className="login-form-side">
          <div className="login-form-inner">
            <p className="login-eyebrow">内部协作平台</p>
            <h2 className="login-title">欢迎回来</h2>
            <p className="login-subtitle">登录以继续协作</p>

            <form onSubmit={submit} className="login-form">
              <div className="login-field">
                <label className="login-label" htmlFor="username">
                  用户名
                </label>
                <input
                  id="username"
                  className="login-input"
                  placeholder="请输入用户名"
                  value={u}
                  onChange={(e) => setU(e.target.value)}
                  autoComplete="username"
                  autoFocus
                />
              </div>

              <div className="login-field">
                <label className="login-label" htmlFor="password">
                  密码
                </label>
                <div className="login-pwd-wrap">
                  <input
                    id="password"
                    className="login-input"
                    type={showPwd ? "text" : "password"}
                    placeholder="请输入密码"
                    value={p}
                    onChange={(e) => setP(e.target.value)}
                    autoComplete="current-password"
                  />
                  <button
                    type="button"
                    className="login-eye"
                    aria-label={showPwd ? "隐藏密码" : "显示密码"}
                    onClick={() => setShowPwd((s) => !s)}
                  >
                    {showPwd ? <EyeOffIcon /> : <EyeIcon />}
                  </button>
                </div>
              </div>

              {err && <p className="login-error">{err}</p>}

              <button className="login-submit" type="submit" disabled={loading}>
                {loading ? (
                  <>
                    <span className="login-spinner" />
                    登录中…
                  </>
                ) : (
                  "登 录"
                )}
              </button>
            </form>

            <p className="login-footer">账号由管理员开通 · 纯内部使用</p>
          </div>
        </div>
      </div>
    </div>
  );
}

function EyeIcon() {
  return (
    <svg
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  );
}

function EyeOffIcon() {
  return (
    <svg
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24" />
      <line x1="1" y1="1" x2="23" y2="23" />
    </svg>
  );
}
